<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AdSentinel</AssemblyName>
    <RootNamespace>AdSentinel</RootNamespace>
    <Version>1.2.1</Version>
    <FileVersion>1.2.1</FileVersion>
    <Product>AdSentinel 广告哨兵</Product>
    <Description>开源 Windows 弹窗广告拦截器</Description>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="assets\builtin_rules.json" />
  </ItemGroup>

</Project>
